export const AllProducts = [
    {
      id: 1,
      name: "Bamboo Pibers",
      img: ["../../public/imgs/BambooPibers.jpg"],
      price: 50,
      category: "SHAMPOO",
      mark: "Mani Moisture",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 2,
      name: "Bico Borrifador Aplicador de Toppik",
      img: ["../../public/imgs/Turmericlemon.jpg"],
      price: 60.5,
      category: "BODY",
      mark: "PRESSED",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    // {
    //   id:3,
    //   name: "Wellnesshot",
    //   img: ["./Wellnesshot.jpg"],
    //   price: 70,
    //   category: "BODY",
    //   mark: "PRESSED",
    //   shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
    //   Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
    //   inCart: false,
    //   count: 0,
    //   total: 0
    // },
    // {
    //   id: 4,
    //   name: "Airspun",
    //   img: ["./Airspun.jpg"],
    //   price: 60.5,
    //   category: "FACE",
    //   mark: "PRESSED",
    //   shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
    //   Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
    //   inCart: false,
    //   count: 0,
    //   total: 0
    // },
    // {
    //   id: 5,
    //   name: "Bico Borrifador Aplicador de Toppik",
    //   img: ["./Gabrielle Chanel.jpg"],
    //   price: 90.5,
    //   category: "Perfume",
    //   mark: "PRESSED",
    //   shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
    //   Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
    //   inCart: false,
    //   count: 0,
    //   total: 0
    // },
    // {
    //   id: 6,
    //   name: "Ginger Boney",
    //   img: ["./Ginger Boney"],
    //   price: 60.5,
    //   category: "BODY",
    //   mark: "PRESSED",
    //   shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
    //   Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
    //   inCart: false,
    //   count: 0,
    //   total: 0
    // },
    // {
    //   id: 7,
    //   name: "Ex Prunis",
    //   img: ["./Ex Prunis.jpg"],
    //   price: 60.5,
    //   category: "BODYOIL",
    //   mark: "PHAEDRA",
    //   shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
    //   Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
    //   inCart: false,
    //   count: 0,
    //   total: 0
    // },
    // {
    //   id: 8,
    //   name: "Relieft",
    //   img: ["./Relieft.jpg"],
    //   price: 83.5,
    //   category: "SHOWER",
    //   mark: "PHARMA HEMP",
    //   shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
    //   Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
    //   inCart: false,
    //   count: 0,
    //   total: 0
    // },
    // {
    //   id: 9,
    //   name: "CREAM-EYE",
    //   img: ["./Annmarie.jpg"],
    //   price: 32,
    //   category: "EYES",
    //   mark: "ANNMARIE",
    //   shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
    //   Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
    //   inCart: false,
    //   count: 0,
    //   total: 0
    // }
  ];